version: '3.1'

services:

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    networks: 
      - app-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    environment:
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
    depends_on:
      - backend
    networks: 
      - app-network

  jenkins:
    build:
      context: .
      dockerfile: Dockerfile
    user: root
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker:/usr/bin/docker
    ports:
      - 8080:8080
    privileged: true
    networks: 
      - app-network
    depends_on:
      - backend
      - frontend

volumes:
  jenkins_home:

networks:
  app-network:
