version: '3.1'

services:

  db:
    image: postgres
    restart: always
    networks:
      - database-server
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - ./setup/DB_script/erd.sql:/docker-entrypoint-initdb.d/erd.sql
    ports:
      - "5432:5432"
    privileged: true

  pdadmin:
    image: dpage/pgadmin4
    restart: always
    networks:
      - database-server
    ports:
      - "81:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: example@gmail.com
      PGADMIN_DEFAULT_PASSWORD: example
      PGADMIN_SERVER_MODE: 'True'
      PGADMIN_SERVER_JSON_FILE: /pgadmin4/servers.json
    volumes:
      - ./setup/servers.json:/pgadmin4/servers.json
    depends_on:
      - db
    links:
      - db
    privileged: true

  # react-app:
  #   build: ./client
  #   image: react-image
  #   container_name: react-app
  #   ports:
  #     - "3000:3000"
  #   environment:
  #     - CHOKIDAR_USEPOLLING=true
  #     - WATCHPACK_POLLING=true
  #   depends_on:
  #     - db

  jenkins:
    image: jenkins/jenkins:lts
    user: root
    ports:
      - 8080:8080
      - 50000:50000
    # environment:
    #   - JENKINS_OPTS=--prefix=/jenkins
    #   - JAVA_OPTS=-Djenkins.install.runSetupWizard=false
    restart: always
    privileged: true

volumes:
  postgres:
  jenkins_home:

networks:
  database-server: