FROM jenkins/jenkins:lts
# FROM jenkinsci/blueocean
# COPY plugins.txt /usr/share/jenkins/ref/plugins.txt
# COPY script.groovy /usr/share/jenkins/ref/init.groovy.d/setup.groovy

# FROM jenkins/jenkins:lts
# COPY plugins.txt /usr/share/jenkins/ref/plugins.txt
# COPY script.groovy /usr/share/jenkins/ref/init.groovy.d/setup.groovy
# RUN jenkins-plugin-cli -f /usr/share/jenkins/ref/plugins.txt


# FROM jenkins/jenkins:lts
# LABEL maintainer="Student Debil <student.debil@example.com>"

# ENV JENKINS_USER admin
# ENV JENKINS_PASS admin

# ENV JAVA_OPTS -Djenkins.install.runSetupWizard=false

# COPY plugins.txt /usr/share/jenkins/ref/plugins.txt
# RUN /usr/local/bin/install-plugins.sh < /usr/share/jenkins/ref/plugins.txt
# USER root
# RUN apt-get clean
# USER jenkins


# FROM jenkins/jenkins:alpine
# MAINTAINER   VinothKumar P <vinothkumar.P@Yahoo.com>
# ENV JENKINS_USER admin
# ENV JENKINS_PASS admin

# # Skip initial setup
# ENV JAVA_OPTS -Djenkins.install.runSetupWizard=false


# COPY plugins.txt /usr/share/jenkins/plugins.txt
# RUN /usr/local/bin/install-plugins.sh < /usr/share/jenkins/plugins.txt
# USER root
# RUN apk add docker
# RUN apk add py-pip

# USER jenkins